---
services:
    exporter:
        build: .
        container_name: exporter
        environment:
            TESLA_WALLBOX_IP: 10.10.0.39
            DEBUG: "true"
            KEEP_POWER_METER: "true"

    influxdb:
        image: influxdb:latest
        container_name: influx
        volumes:
            - ./influx-data:/var/lib/influxdb2:rw
            - ./influx-config:/etc/influxdb2:rw
        ports:
            - "8086:8086"
        environment:
            DOCKER_INFLUXDB_INIT_MODE: setup
            DOCKER_INFLUXDB_INIT_USERNAME: admin
            DOCKER_INFLUXDB_INIT_PASSWORD: supers3cret
            DOCKER_INFLUXDB_INIT_ORG: whatever
            DOCKER_INFLUXDB_INIT_BUCKET: dontcare
            DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: KoYlsQXuKGvoJrpfcbmQeGXyr6HdYYdRmcn3et84vHKAwiv9Lv3vNICwP7qyk6n-DgwEXxYKHkls_Jv2jeNn3w==

    grafana:
        image: grafana/grafana-oss
        container_name: grafana
        ports:
            - "3000:3000"
        volumes:
            - ./grafana_provision:/etc/grafana/provisioning
            - ./grafana_dashboards:/etc/dashboards

    telegraf:
        image: telegraf
        container_name: telegraf
        volumes:
            - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro