---
services:
    exporter:
        build: .
        container_name: exporter
        environment:
            TESLA_WALLBOX_IP: 10.10.0.39
            DEBUG: "true"

    influxdb:
        image: influxdb:latest
        container_name: influx
        volumes:
            - influx-data:/var/lib/influxdb2:rw
            - influx-config:/etc/influxdb2:rw
        ports:
            - "8086:8086"
        environment:
            DOCKER_INFLUXDB_INIT_MODE: setup
            DOCKER_INFLUXDB_INIT_USERNAME: admin
            DOCKER_INFLUXDB_INIT_PASSWORD: supers3cret
            DOCKER_INFLUXDB_INIT_ORG: whatever
            DOCKER_INFLUXDB_INIT_BUCKET: dontcare

volumes:
    influx-config:
    influx-data:
