{
 "title": "Current session",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "arbeitspreis", "label": "Cent / kWh", "query": "28.0" }
  ]
 },
 "panels": [
  {
   "title": "Charging power",
   "type": "stat",
   "description": "Current charging power",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dontcare\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"phase_a_current\" or r[\"_measurement\"] == \"phase_a_voltage\" or r[\"_measurement\"] == \"phase_b_current\" or r[\"_measurement\"] == \"phase_b_voltage\" or r[\"_measurement\"] == \"phase_c_current\" or r[\"_measurement\"] == \"phase_c_voltage\")\n  |> filter(fn: (r) => r[\"_field\"] == \"gauge\")\n  |> pivot(columnKey: [\"_measurement\"], rowKey: [\"_time\"], valueColumn: \"_value\" )\n  |> map(fn: (r) => ({ _time: r._time, _field: \"Ladeleistung\", _value: r.phase_a_voltage * r.phase_a_current + r.phase_b_voltage * r.phase_b_current + r.phase_c_voltage * r.phase_c_current}))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Dispensed energy",
   "type": "stat",
   "description": "Dispensed energy in this session",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dontcare\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"session_energy\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> set(key: \"_field\", value: \"Energie\")"
    }
   ]
  },
  {
   "title": "Currently charging?",
   "type": "stat",
   "description": "Is the vehicle currently charging? Red = no, Green = yes",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dontcare\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"contactor_closed\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Vehicle connected?",
   "type": "stat",
   "description": "Is a vehicle connected? Red = no, green = yes",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dontcare\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vehicle_connected\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Connected for",
   "type": "stat",
   "description": "Time the vehicle is plugged in",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dontcare\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"session_duration\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Costs",
   "type": "stat",
   "description": "Currently accumulated costs",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dontcare\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"session_energy\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> map(fn: (r) => ({ r with _value: r._value / 1000.0 * ${arbeitspreis} / 100.0 }))"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dontcare\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"handle_temperature\" or r[\"_measurement\"] == \"mcu_temperature\" or r[\"_measurement\"] == \"pcb_temperature\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, _measurement:\n    if r._measurement == \"mcu_temperature\" then \"Microcontroller\"\n    else if r._measurement == \"handle_temperature\" then \"Handle\"\n    else if r._measurement == \"pcb_temperature\" then \"PCB\"\n    else \"unbekannt\"}))"
    }
   ]
  }
 ]
}